branch-defaults:
  master:
    environment: $CIRCLE_BRANCH
global:
  application_name: $APP_NAME
  default_ec2_keyname: $EC2_KEY
  default_platform: $NODE_TYPE
  default_region: ${AWS_DEFAULT_REGION}
  sc: git